models/Equipo.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "equipo".
 *
 * @property string $nomequipo
 * @property string|null $director
 *
 * @property Ciclista[] $ciclistas
 */
class Equipo extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'equipo';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nomequipo'], 'required'],
            [['nomequipo'], 'string', 'max' => 25],
            [['director'], 'string', 'max' => 30],
            [['nomequipo'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'nomequipo' => 'Nomequipo',
            'director' => 'Director',
        ];
    }

    /**
     * Gets query for [[Ciclistas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCiclistas()
    {
        return $this->hasMany(Ciclista::class, ['nomequipo' => 'nomequipo']);
    }
}

controllers/EquipoController.php
<?php

namespace app\controllers;

use app\models\Equipo;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Ciclista;
use Yii;
use yii\helpers\Url;
/**
 * EquipoController implements the CRUD actions for Equipo model.
 */
class EquipoController extends Controller
{
    public static $standardimage = '@webroot/path/to/standard-image.jpg';
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Equipo models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Equipo::find(),
            
            'pagination' => [
                'pageSize' => 50
            ],
            /*
            'sort' => [
                'defaultOrder' => [
                    'nomequipo' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Equipo model.
     * @param string $nomequipo Nomequipo
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($nomequipo)
    {
        $ciclistas = new ActiveDataProvider([
            'query' => Ciclista::find()->select("dorsal,nombre,edad")->where("nomequipo='" .$nomequipo . "'")
        ]);
        
        return $this->render('view', [
            'model' => $this->findModel($nomequipo),
            'ciclistas' => $ciclistas
        ]);
    }

    /**
     * Creates a new Equipo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Equipo();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'nomequipo' => $model->nomequipo]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Equipo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $nomequipo Nomequipo
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($nomequipo)
    {
        $model = $this->findModel($nomequipo);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'nomequipo' => $model->nomequipo]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Equipo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $nomequipo Nomequipo
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($nomequipo)
    {
        $this->findModel($nomequipo)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Equipo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $nomequipo Nomequipo
     * @return Equipo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($nomequipo)
    {
        if (($model = Equipo::findOne(['nomequipo' => $nomequipo])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public static function imagen($nomequipo) {
        $imagenes = ['Amore Vita.jpg', 'Artiach.jpg', 'Banesto.jpg',
        'Bresciali-Refin.jpg', 'Carrera.jpg', 'Castorama.jpg',
        'Euskadi.jpg', 'Gatorade.jpg', 'Gewiss.jpg',
        'Lotus Festina.jpg', 'Mercatone Uno.jpg', 'Jolly Club.jpg',
        'Kelme.jpg', 'Motorola.jpg', 'Navigare.jpg',
        'ONCE.jpg', 'PDM.jpg', 'Seguros Amaya.jpg',
        'Telecom.jpg', 'TVM.jpg', 'Wordperfect.jpg'];
        if (in_array($nomequipo . '.jpg', $imagenes)) {
            return Url::to('@web/img/logos/' . $nomequipo . '.jpg');
        } else {
            return Url::to('@web/img/logos/equipo-standard.jpg');
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Equipo;
use app\models\Ciclista;
use yii\data\ActiveDataProvider;
use app\models\Etapa;
use yii\db\Expression;
use app\controllers\CiclistaController;
use yii\data\SqlDataProvider;
use app\models\Maillot;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    public function actionCrear() {
        return $this->render('crear',[
           "Texto" => "Página para crear vueltas"
        ]);
    }
    
    
    public function actionEquipos() {
        $teams = new ActiveDataProvider([
            'query'=>Equipo::find()->select("nomequipo,director"),
            'pagination' => [
                'pageSize' => -1, // Muestro todos los registros.
            ]
        ]);
        
        

        return $this->render('vista', [
            "resultados"=> $teams,
            "campos"=> ['nomequipo','director']
       ]);    
    }
    
    public function actionClasificacion() {
        $dataProvider = new ActiveDataProvider([
           'query' => Ciclista::find()->select("*") 
        ]);
        foreach($dataProvider->getModels() as $model) {
            
        }
        count(Ciclista::hasMany("etapa",['dorsal'])->asArray());
    }
    
    
    
    public function actionSimular()
    {
        $etapas = Etapa::find()->all();
        $equipos = Equipo::find()->all();
        $ciclistas = CiclistaController::inicializar($equipos);
        $ciclistas_arr = $ciclistas->getModels();       
        $datos = [];   
        Yii::$app->db->createCommand('DELETE FROM lleva;')->execute();   
        foreach($etapas as $etapa) { // Por cada etapa
            $index = (string) $etapa->numetapa;
            $minTiempoVolante = $minTiempoPuerto = null;
            $datos[$index] = '<h2 class="etapa-titulo text-center jumbotron-fluid">' . $etapa->salida . ' ' . $etapa->llegada  . ' ' . $etapa->kms . ' Kms</h2>';      
            $puertos = $etapa->setPuertos(); // Colocamos los puertos dentro de la etapa
            $metas_volantes = $etapa->colocarMetasVolantes(); // Colocamos las metas volantes dentro de la etapa
            $etapa->run($etapa,$ciclistas,$datos,$index,$metas_volantes,$minTiempoVolante,$puertos,$minTiempoPuerto); // Simulamos la etapa
            $etapa->resultados($ciclistas, $ciclistas_arr,$datos,$index); // Computamos los resultados 
        }

        return $this->render('simular', [
            'datos' => $datos,
            'clasificacion' => $ciclistas_arr,
            'ciclistas' => $ciclistas,
            'etapas' => $etapas,
            'equipos' => $equipos,
        ]);
    }
 
    public function actionIniciarvuelta()
    {
        $etapas = new ActiveDataProvider([
            'query' => Etapa::find()->select("*"),
            'pagination' => [
                'pageSize' => -1, // Muestro todos los registros.
            ]
        ]);
        $equipos = new ActiveDataProvider([
            'query' => Equipo::find()->select("*"),
            'pagination' => [
                'pageSize' => -1, // Muestro todos los registros.
            ]
        ]);
        return $this->render('iniciarvuelta',[
            'equipos' => $equipos,
            'etapas' => $etapas,
       
        ]);   
    }
    
    public function renderSimEtapa($etapas, $equipos, $ciclistas)
    {
        return $this->render('sim_etapa',[
            'ciclistas' => $ciclistas,
            'etapas' => $etapas,
            'equipos' => $equipos
        ]);
    }
    /**
     * Devuelve en un DataProvider la lista de los ciclistas que han ganado un
     * maillot con un código determinado 
     * 
     * @param type $codigo
     * @return SqlDataProvider
     */
    public static function ciclistasConMaillots($codigo) {
        return new SqlDataProvider([
           'sql' => 'SELECT DISTINCT l.dorsal, c.nombre, e.numetapa AS etapa, e.salida, e.llegada
                        FROM etapa e
                        INNER JOIN lleva l ON e.dorsal=l.dorsal
                        INNER JOIN ciclista c on c.dorsal=l.dorsal
                        INNER JOIN maillot m ON l.código = m.código
                        WHERE m.código ="' . $codigo . '"',
            'pagination' => false
        ]);
    }
    /**Devuelve en un DataProvider la lista de los equipos, con la cantidad de
     * maillots que han ganado de cada tipo
     * 
     * @param type $codigo
     * @return SqlDataProvider
     */
    public static function equiposConMaillotsTipo($codigo) {
        return new SqlDataProvider([
           'sql' => 'SELECT e.nomequipo, COUNT(*) AS maillots 
                        FROM lleva l INNER JOIN ciclista c ON l.dorsal = c.dorsal
                          INNER JOIN equipo e ON c.nomequipo=e.nomequipo
                          INNER JOIN maillot m ON l.código = m.código
                        WHERE m.código="' . $codigo . '"
                        GROUP BY e.nomequipo, l.código
                        ORDER BY m.código asc, maillots DESC',
            'pagination' => false
        ]);
    }
    
    public static function maillotsYDineroPorCiclista() {
        return new SqlDataProvider([
            'sql' => 'SELECT c.dorsal, c.nombre, COUNT(l.dorsal) AS maillots, SUM(m.premio) AS "Dinero en premios"
                        FROM ciclista c left JOIN lleva l ON c.dorsal = l.dorsal
                        LEFT JOIN maillot m ON l.código=m.código
                        GROUP BY c.dorsal
                        ORDER BY 4 desc',
            'pagination' => false
        ]);
    }
    
    public static function maillotsYDineroPorEquipo() {
        return new SqlDataProvider([
            'sql' => 'SELECT  e.nomequipo, COUNT(l.dorsal) AS maillots, SUM(m.premio) AS "Dinero ganado"
                        FROM equipo e INNER JOIN ciclista c USING (nomequipo) LEFT JOIN lleva l ON c.dorsal = l.dorsal
                        LEFT JOIN maillot m ON l.código=m.código
                        GROUP BY e.nomequipo
                        ORDER BY 3 desc',
            'pagination' => false
        ]);
    }
    
    public static function puertosPorCiclista() {
        return new SqlDataProvider([
            'sql' => 'SELECT c.dorsal, c.nombre, COUNT(*) AS "Puertos Ganados"
                        FROM ciclista c INNER JOIN puerto p USING (dorsal)
                        GROUP BY c.dorsal',
            'pagination' => false
        ]);
    }
    
    public static function puertosPorEquipo() {
        return new SqlDataProvider([
            'sql' => 'SELECT c.nomequipo, COUNT(*) AS "Puertos Ganados"
                        FROM ciclista c INNER JOIN puerto p USING (dorsal)
                        GROUP BY c.nomequipo',
            'pagination' => false
        ]);
    }
    
    public static function ganadoresMaillotFinal() {
        return new SqlDataProvider([
            'sql' => 'SELECT m.color, m.tipo, c.dorsal, c.nombre, e.nomequipo, e.director
                        FROM (SELECT * FROM lleva
                        WHERE numetapa=(SELECT MAX(numetapa) FROM etapa))AS l
                        INNER JOIN maillot m USING (código)
                        INNER JOIN ciclista c USING (dorsal)
                        INNER JOIN equipo e USING (nomequipo)
                      UNION
                      SELECT m.color, m.tipo, c.dorsal, c.nombre, e.nomequipo, e.director

views/equipo/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\Equipo $model */
/** @var yii\widgets\ActiveForm $form */
?>
<?= Html::a('Volver', ['equipo/index'], ['class' => 'btn btn-outline-primary']) ?>
<div class="equipo-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nomequipo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'director')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-outline-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/equipo/_item.php
<?php
use yii\widgets\DetailView;
use yii\grid\GridView;
use app\controllers\CiclistaController;
use yii\grid\ActionColumn;
use yii\helpers\Url;
use yii\helpers\Html;
use app\controllers\EquipoController;


?>
<div class="etapa-item">
    <h2 class="col-md-6 text-center">EQUIPO <?=$model->nomequipo ?></h2><h2 class="col-md-6 text-center">Ciclistas</h2>
</div>

<div class="etapa-item">
    <div class="nombre-imagen column-md-4">
        <?= Html::img(EquipoController::imagen($model->nomequipo))?>
    </div>
    <div class="column-md-4">
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                ['attribute' => 'nomequipo',
                 'label' => 'Nombre'],
                'director',
            ],
        ]) ?>
        <p class="text-center"><?= Html::a('Editar Equipo', ['equipo/update', 'nomequipo'=> $model->nomequipo], ['class'=>'btn btn-outline-primary']) ?></p>
        <p class="text-center"><?= Html::a('Delete', Url::to(['equipo/delete', 'nomequipo' => $model->nomequipo, '_csrf' => Yii::$app->request->csrfToken]), [
            'class'=>'btn btn-outline-danger',
            'data-confirm' => 'Are you sure you want to delete this item?',
            'data-method' => 'post',
                ]); ?></p>
        <p class="text-center"><?= Html::a('Añadir ciclista', ['ciclista/create'], ['class'=>'btn btn-outline-success']) ?></p>    
    </div>
    <div class="column-md-4">
        
        <?= GridView::widget([
            'dataProvider' => CiclistaController::ciclistasDelEquipo($model->nomequipo),
            'columns' => [
                'dorsal',
                'nombre',
                'edad',
                [
                    'class' => ActionColumn::className(),
                    'urlCreator' => function ($action, $model, $key, $index) {
                        $url = ['ciclista/' . $action, 'dorsal' => $model->dorsal];
                        return Url::to($url);
                    },
                ],

            ],
            'summary' => '',
        ]); ?>
        
    </div>
</div>

views/equipo/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Equipo $model */

$this->title = 'Create Equipo';
$this->params['breadcrumbs'][] = ['label' => 'Equipos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="equipo-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/equipo/index.php
<?php
use yii\helpers\Html;
use yii\widgets\ListView;

/** @var yii\web\View $this */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Equipos';
?>
<div class="equipo-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Añadir Equipo', ['create'], ['class'=>'btn btn-outline-success']) ?>
        <?= Html::a('Volver', ['site/crear'], ['class'=>'btn btn-outline-primary']) ?>
    </p>
   <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_item', 
        'summary' => '', 
        'emptyText' => 'No se encontraron Equipos', 
        'pager' => false,
    ]); ?>
</div>

views/equipo/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Equipo $model */

$this->title = 'Update Equipo: ' . $model->nomequipo;
$this->params['breadcrumbs'][] = ['label' => 'Equipos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->nomequipo, 'url' => ['view', 'nomequipo' => $model->nomequipo]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="equipo-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/equipo/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;
use app\models\Ciclista;
use yii\grid\ActionColumn;
use yii\helpers\Url;

/** @var yii\web\View $this */
/** @var app\models\Equipo $model */

$this->title = $model->nomequipo;
$this->params['breadcrumbs'][] = ['label' => 'Equipos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="equipo-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'nomequipo' => $model->nomequipo], ['class' => 'btn btn-outline-primary']) ?>
        <?= Html::a('Delete', ['delete', 'nomequipo' => $model->nomequipo], [
            'class' => 'btn btn-outline-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
         <?= Html::a('Volver', ['index'], ['class' => 'btn btn-outline-primary']) ?>
    
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'nomequipo',
            'director',
        ],
    ]) ?>
     <?= GridView::widget([
        'dataProvider' => $ciclistas,
        'columns' => [
            [
                'attribute' => 'nombre',
                'header' => 'Corredor',
            ],
            'dorsal',
            'edad',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, Ciclista $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'dorsal' => $model->dorsal]);
                },
            ],
        ],
        'rowOptions' => function ($model, $key, $index, $grid) {
            $options = ['class' => ''];

            if ($index < 3) {
                $options['class'] .= ' highlighted-row';
            }

            return $options;
        },
    ]); ?>
    <p>
        <?= Html::a('Añadir Ciclista', ['ciclista/create'], ['class' => 'btn btn-outline-success']) ?>
    </p>
   
</div>