controllers/EtapaController.php
<?php

namespace app\controllers;

use app\models\Etapa;
use app\models\Puerto;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Yii;


/**
 * EtapaController implements the CRUD actions for Etapa model.
 */
class EtapaController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Etapa models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Etapa::find(),
            
            'pagination' => [
                'pageSize' => 50
            ],
            /*
            'sort' => [
                'defaultOrder' => [
                    'numetapa' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Etapa model.
     * @param int $numetapa Numetapa
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($numetapa)
    {
        $puertos = new ActiveDataProvider([
            "query" => Puerto::find()->select("*")->where("numetapa='" . $numetapa . "'")->distinct()
        ]);
        
        return $this->render('view', [
            'model' => $this->findModel($numetapa),
            'puertos' => $puertos
        ]);
    }

    /**
     * Creates a new Etapa model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Etapa();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'numetapa' => $model->numetapa]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Etapa model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $numetapa Numetapa
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($numetapa)
    {
        $model = $this->findModel($numetapa);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'numetapa' => $model->numetapa]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Etapa model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $numetapa Numetapa
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($numetapa)
    {
        $this->findModel($numetapa)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Etapa model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $numetapa Numetapa
     * @return Etapa the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($numetapa)
    {
        if (($model = Etapa::findOne(['numetapa' => $numetapa])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    /** Realiza la simulacion de una etapa
     * 
     */
    public function actionSimular() {
        $ciclistas = json_decode(Yii::$app->request->post('ciclistas'), true);
        $etapas = json_decode(Yii::$app->request->post('etapas'), true);
        $index = Yii::$app->request->post('index');
        
        $etapa = $etapas->find()->where("ID=" . $index);
        $datos = "<h2>Etapa: " . $etapa->id . " " . $etapa->salida . " " . $etapa->llegada . "</h2>";
        $datos .= '<h2>---------------- ' . $etapa->salida . ' ' . $etapa->llegada  . ' ' . $etapa->kms . ' Kms ----------------------</h2>';
        $puertos = new ActiveDataProvider([
            'query' => Puerto::find()->select('*')->where("numetapa=" . $etapa->numetapa)
        ]);

        $metas_volantes = $etapa->colocarMetasVolantes();

        // Colocamos los puertos en un km aleatorio de la etapa.
        foreach($puertos->getModels() as $puerto) {
            $puerto->km = rand(5,$etapa->kms);
        }
        // Por cada km de la etapa
         for($i = 1; $i<= $etapa->kms; $i++) {
            // Por cada ciclista
            $datos .= "<h2>---- KM " . $i . " ----</h2>";
            foreach($ciclistas->getModels() as $ciclista) {
                // Se suma un tiempo en segundos con un 5% de posibilidades de
                // tener la posibilida de hacer un sprint especial
                $temp = (rand(0,100) > 1)? rand(45,180):rand(36,180);
                // Si el tiempo es muy bajo, hace un sprint
                $ciclista->sprints += ($temp<45)?1:0;
                // Suma los segundos al tiempo de la etapa y al tiempo total.
                $ciclista->tiempo += $temp;
                $ciclista->tiempo_total += $temp;
                // Imprime el tiempo de todos los ciclistas (Debug).
                if ($i%5==0) { // cada 5 Kms (Para no sobrecargar la memoria disponible).
                    $datos .= '<p>' . $ciclista->nombre
                           . ". Tiempo: " . $ciclista->getTiempoEtapa()
                            . " Tiempo Total: " . $ciclista->getTiempoTotal()
                            . (($temp<45)?"¡SPRINT ESPECIAL!":"") . '</p>';
                }
            }
            // Si hay metas volantes en la etapa
            if ($metas_volantes != null) {
                // Por cada meta volante
                foreach($metas_volantes as $volante) {
                    // Si hemos llegado a una meta volante
                    if($i==$volante) {
                        $minTiempoVolante = new Ciclista();
                        $minTiempoVolante->tiempo = 100000000;
                        // Al final de la etapa, por cada ciclista:
                        foreach($ciclistas->getModels() as $ciclista) {
                            // Comprobamos quién ha ganado la etapa (completado en menos tiempo).
                            $minTiempoVolante = ($ciclista->tiempo < $minTiempoVolante->tiempo)? $ciclista:$minTiempoVolante;
                        }
                        // Al ciclista ganador se le suman los puntos del puerto.
                        $minTiempoVolante->metas_volantes += 1;
                    }
                }
            }

            // Comprobamos si han llegado a un puerto
            foreach($puertos->getModels() as $puerto) {
                if ($i==$puerto->km) {
                    // Creamos una Instancia de Ciclista con tiempo máximo para ver quién ha ganado el puerto
                    $minTiempoPuerto = new Ciclista();
                    $minTiempoPuerto->tiempo = 100000000;
                    // Al final de la etapa, por cada ciclista:
                    foreach($ciclistas->getModels() as $ciclista) {
                        // Comprobamos quién ha ganado la etapa (completado en menos tiempo).
                        $minTiempoPuerto = ($ciclista->tiempo < $minTiempoPuerto->tiempo)? $ciclista:$minTiempoPuerto;
                    }
                    // Al ciclista ganador se le suman los puntos del puerto.
                    $minTiempoPuerto->puntos_puerto = $minTiempoPuerto->puntos_puerto + $puerto->getPuntos();
                    // Actualizamos la tabla puerto con el ganador de cada puerto
                    Yii::$app->db->createCommand(
                        'UPDATE puerto SET dorsal=' . $minTiempoPuerto->dorsal . ' WHERE nompuerto="' . $puerto->nompuerto . '";')->execute();
                    $datos .= '<p>El ciclista ' . $minTiempoPuerto->nombre . ' ha ganado el puerto ' . $puerto->nompuerto . 'con un tiempo de ' . $minTiempoPuerto->getTiempoEtapa() . '</p>';
                }
            }


        }

        // Creamos una Instancia de Ciclista con sprints a 0 para ver quién ha hecho más sprints en la etapa
        $maxSprints = new Ciclista();
        $maxSprints->sprints = 0;
        // Creamos una Instancia de Ciclista con tiempo máximo para ver quién ha ganado la etapa
        $minTiempo = new Ciclista();
        $minTiempo->tiempo = 100000000;

        // Creamos una Instancia de Ciclista con puntos_puerto 0 para ver quién ha ganado la montaña.
        $maxPuertos = new Ciclista();
        $maxPuertos->puntos_puerto = 0;

        // Creamos una Instancia de Ciclista con metas_volantes 0 para ver quién ha hecho más metas volantes.
        $maxMetasVolantes= new Ciclista();
        $maxMetasVolantes->metas_volantes = 0;

        // Ordenamos la lista de ciclistas
        $ciclistas_arr = Ciclista::ordenar($ciclistas_arr,"tiempo");

        // asignamos puntos en función del tiempo
        $etapa->assignPoints($ciclistas_arr);

        // mostramos la clasificación de la etapa
        $datos .= '<h2>CLASIFICACIÓN:</h2>';
        $i = 0;
        foreach($ciclistas_arr as $ciclista) {  
            $datos .= '<p>' . ($i + 1) . 'º: ' . $ciclista->nombre . ' ' . $ciclista->getTiempoEtapa() . $ciclista->puntos . '</h2>';
            $i++;
            if ($i>=20) {

controllers/PuertoController.php
<?php

namespace app\controllers;

use app\models\Puerto;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PuertoController implements the CRUD actions for Puerto model.
 */
class PuertoController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Puerto models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Puerto::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'nompuerto' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Puerto model.
     * @param string $nompuerto Nompuerto
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($nompuerto)
    {
        return $this->render('view', [
            'model' => $this->findModel($nompuerto),
        ]);
    }

    /**
     * Creates a new Puerto model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Puerto();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['etapa/view', 'numetapa' => $model->numetapa]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Puerto model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $nompuerto Nompuerto
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($nompuerto)
    {
        $model = $this->findModel($nompuerto);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['etapa/view', 'numetapa' => $model->numetapa]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Puerto model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $nompuerto Nompuerto
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($nompuerto)
    {
        $this->findModel($nompuerto)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Puerto model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $nompuerto Nompuerto
     * @return Puerto the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($nompuerto)
    {
        if (($model = Puerto::findOne(['nompuerto' => $nompuerto])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public static function puertosDeLaEtapa($numetapa) {
        return new ActiveDataProvider([
            'query' => Puerto::find()->select('nompuerto,altura,categoria,pendiente,numetapa')->where('numetapa="' . $numetapa .'"')
        ]);
    }
}

views/etapa/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\Etapa $model */
/** @var yii\widgets\ActiveForm $form */
?>
<p><?= Html::a('Volver', ['etapa/index'], ['class' => 'btn btn-outline-primary']) ?></p>
<div class="etapa-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'numetapa')->textInput() ?>

    <?= $form->field($model, 'kms')->textInput() ?>

    <?= $form->field($model, 'salida')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'llegada')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'dorsal')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-outline-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/etapa/_item.php
<?php
use yii\widgets\DetailView;
use yii\grid\GridView;
use app\models\Puerto;
use app\controllers\PuertoController;
use yii\grid\ActionColumn;
use yii\helpers\Url;
use yii\helpers\Html;

?>
<h2>ETAPA <?=$model->numetapa ?></h2>
<div class="etapa-item" style="display:flex;justify-content: space-evenly;">
    <div class="nombre-imagen column-md-4">
        <?= Html::img("@web/img/bing/etapas.jpg")?>
    </div>
    <div class="column-md-4">
        <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            ['attribute' => 'numetapa',
             'label' => 'Etapa'],
            'salida',
            'llegada',
            'kms'
        ],
    ]) ?>
    <p><?= Html::a('Editar Etapa', ['etapa/update', 'numetapa'=> $model->numetapa], ['class'=>'btn btn-outline-primary']) ?></p>
    <p><?= Html::a('Borrar Equipo', ['etapa/delete', 'numetapa'=> $model->numetapa], ['class'=>'btn btn-outline-danger']) ?></p>
    <p><?= Html::a('Añadir Puerto', ['puerto/create'], ['class'=>'btn btn-outline-success']) ?></p>    
    </div>
    <div class="column-md-4">
        <?= GridView::widget([
            'dataProvider' => PuertoController::puertosDeLaEtapa($model->numetapa),
            'columns' => [
                ['attribute' => 'nompuerto',
                'label' => 'Puerto'],
                'altura',
                'categoria',
                'pendiente',
                [
                    'class' => ActionColumn::className(),
                    'urlCreator' => function ($action, $model, $key, $index) {
                        $url = ['puerto/' . $action, 'nompuerto' => $model->nompuerto];
                        return Url::to($url);
                    },
                ],

            ],
            'summary' => '',
        ]); ?>
        
    </div>
</div>

views/etapa/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Etapa $model */

$this->title = 'Create Etapa';
$this->params['breadcrumbs'][] = ['label' => 'Etapas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="etapa-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/etapa/index.php
<?php
use yii\helpers\Html;
use yii\widgets\ListView;

/** @var yii\web\View $this */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Etapas';
?>
<div class="etapa-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Añadir Etapa', ['create'], ['class'=>'btn btn-outline-success']) ?>
        <?= Html::a('Volver', ['site/crear'], ['class'=>'btn btn-outline-primary']) ?>
    </p>
   <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_item', 
        'summary' => '', 
        'emptyText' => 'No se encontraron Etapas', 
        'pager' => false,
    ]); ?>
</div>

views/etapa/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Etapa $model */

$this->title = 'Update Etapa: ' . $model->numetapa;
$this->params['breadcrumbs'][] = ['label' => 'Etapas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->numetapa, 'url' => ['view', 'numetapa' => $model->numetapa]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="etapa-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/etapa/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;
use yii\grid\ActionColumn;
use app\models\Puerto;
use yii\helpers\Url;

/** @var yii\web\View $this */
/** @var app\models\Etapa $model */

$this->title = $model->numetapa;
$this->params['breadcrumbs'][] = ['label' => 'Etapas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="etapa-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'numetapa' => $model->numetapa], ['class' => 'btn btn-outline-primary']) ?>
        <?= Html::a('Delete', ['delete', 'numetapa' => $model->numetapa], [
            'class' => 'btn btn-outline-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'numetapa',
            'kms',
            'salida',
            'llegada',
            'dorsal',
        ],
    ]) ?>
    <?= GridView::widget([
        'dataProvider' => $puertos,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'nompuerto',
            'altura',
            'categoria',
            'pendiente',
            'numetapa',
            //'dorsal',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, Puerto $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'nompuerto' => $model->nompuerto]);
                 }
            ],
        ],
    ]); ?>
    <?= Html::a('Añadir Puerto', ['puerto/create'], ['class' => 'btn btn-outline-success']) ?>

</div>