controllers/EquipoController.php
<?php

namespace app\controllers;

use app\models\Equipo;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Ciclista;
use Yii;
use yii\helpers\Url;
/**
 * EquipoController implements the CRUD actions for Equipo model.
 */
class EquipoController extends Controller
{
    public static $standardimage = '@webroot/path/to/standard-image.jpg';
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Equipo models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Equipo::find(),
            
            'pagination' => [
                'pageSize' => 50
            ],
            /*
            'sort' => [
                'defaultOrder' => [
                    'nomequipo' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Equipo model.
     * @param string $nomequipo Nomequipo
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($nomequipo)
    {
        $ciclistas = new ActiveDataProvider([
            'query' => Ciclista::find()->select("dorsal,nombre,edad")->where("nomequipo='" .$nomequipo . "'")
        ]);
        
        return $this->render('view', [
            'model' => $this->findModel($nomequipo),
            'ciclistas' => $ciclistas
        ]);
    }

    /**
     * Creates a new Equipo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Equipo();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'nomequipo' => $model->nomequipo]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Equipo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $nomequipo Nomequipo
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($nomequipo)
    {
        $model = $this->findModel($nomequipo);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'nomequipo' => $model->nomequipo]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Equipo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $nomequipo Nomequipo
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($nomequipo)
    {
        $this->findModel($nomequipo)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Equipo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $nomequipo Nomequipo
     * @return Equipo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($nomequipo)
    {
        if (($model = Equipo::findOne(['nomequipo' => $nomequipo])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public static function imagen($nomequipo) {
        $imagenes = ['Amore Vita.jpg', 'Artiach.jpg', 'Banesto.jpg',
        'Bresciali-Refin.jpg', 'Carrera.jpg', 'Castorama.jpg',
        'Euskadi.jpg', 'Gatorade.jpg', 'Gewiss.jpg',
        'Lotus Festina.jpg', 'Mercatone Uno.jpg', 'Jolly Club.jpg',
        'Kelme.jpg', 'Motorola.jpg', 'Navigare.jpg',
        'ONCE.jpg', 'PDM.jpg', 'Seguros Amaya.jpg',
        'Telecom.jpg', 'TVM.jpg', 'Wordperfect.jpg'];
        if (in_array($nomequipo . '.jpg', $imagenes)) {
            return Url::to('@web/img/logos/' . $nomequipo . '.jpg');
        } else {
            return Url::to('@web/img/logos/equipo-standard.jpg');
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Equipo;
use app\models\Ciclista;
use yii\data\ActiveDataProvider;
use app\models\Etapa;
use yii\db\Expression;
use app\controllers\CiclistaController;
use yii\data\SqlDataProvider;
use app\models\Maillot;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    public function actionCrear() {
        return $this->render('crear',[
           "Texto" => "Página para crear vueltas"
        ]);
    }
    
    
    public function actionEquipos() {
        $teams = new ActiveDataProvider([
            'query'=>Equipo::find()->select("nomequipo,director"),
            'pagination' => [
                'pageSize' => -1, // Muestro todos los registros.
            ]
        ]);
        
        

        return $this->render('vista', [
            "resultados"=> $teams,
            "campos"=> ['nomequipo','director']
       ]);    
    }
    
    public function actionClasificacion() {
        $dataProvider = new ActiveDataProvider([
           'query' => Ciclista::find()->select("*") 
        ]);
        foreach($dataProvider->getModels() as $model) {
            
        }
        count(Ciclista::hasMany("etapa",['dorsal'])->asArray());
    }
    
    
    
    public function actionSimular()
    {
        $etapas = Etapa::find()->all();
        $equipos = Equipo::find()->all();
        $ciclistas = CiclistaController::inicializar($equipos);
        $ciclistas_arr = $ciclistas->getModels();       
        $datos = [];   
        Yii::$app->db->createCommand('DELETE FROM lleva;')->execute();   
        foreach($etapas as $etapa) { // Por cada etapa
            $index = (string) $etapa->numetapa;
            $minTiempoVolante = $minTiempoPuerto = null;
            $datos[$index] = '<h2 class="etapa-titulo text-center jumbotron-fluid">' . $etapa->salida . ' ' . $etapa->llegada  . ' ' . $etapa->kms . ' Kms</h2>';      
            $puertos = $etapa->setPuertos(); // Colocamos los puertos dentro de la etapa
            $metas_volantes = $etapa->colocarMetasVolantes(); // Colocamos las metas volantes dentro de la etapa
            $etapa->run($etapa,$ciclistas,$datos,$index,$metas_volantes,$minTiempoVolante,$puertos,$minTiempoPuerto); // Simulamos la etapa
            $etapa->resultados($ciclistas, $ciclistas_arr,$datos,$index); // Computamos los resultados 
        }

        return $this->render('simular', [
            'datos' => $datos,
            'clasificacion' => $ciclistas_arr,
            'ciclistas' => $ciclistas,
            'etapas' => $etapas,
            'equipos' => $equipos,
        ]);
    }
 
    public function actionIniciarvuelta()
    {
        $etapas = new ActiveDataProvider([
            'query' => Etapa::find()->select("*"),
            'pagination' => [
                'pageSize' => -1, // Muestro todos los registros.
            ]
        ]);
        $equipos = new ActiveDataProvider([
            'query' => Equipo::find()->select("*"),
            'pagination' => [
                'pageSize' => -1, // Muestro todos los registros.
            ]
        ]);
        return $this->render('iniciarvuelta',[
            'equipos' => $equipos,
            'etapas' => $etapas,
       
        ]);   
    }
    
    public function renderSimEtapa($etapas, $equipos, $ciclistas)
    {
        return $this->render('sim_etapa',[
            'ciclistas' => $ciclistas,
            'etapas' => $etapas,
            'equipos' => $equipos
        ]);
    }
    /**
     * Devuelve en un DataProvider la lista de los ciclistas que han ganado un
     * maillot con un código determinado 
     * 
     * @param type $codigo
     * @return SqlDataProvider
     */
    public static function ciclistasConMaillots($codigo) {
        return new SqlDataProvider([
           'sql' => 'SELECT DISTINCT l.dorsal, c.nombre, e.numetapa AS etapa, e.salida, e.llegada
                        FROM etapa e
                        INNER JOIN lleva l ON e.dorsal=l.dorsal
                        INNER JOIN ciclista c on c.dorsal=l.dorsal
                        INNER JOIN maillot m ON l.código = m.código
                        WHERE m.código ="' . $codigo . '"',
            'pagination' => false
        ]);
    }
    /**Devuelve en un DataProvider la lista de los equipos, con la cantidad de
     * maillots que han ganado de cada tipo
     * 
     * @param type $codigo
     * @return SqlDataProvider
     */
    public static function equiposConMaillotsTipo($codigo) {
        return new SqlDataProvider([
           'sql' => 'SELECT e.nomequipo, COUNT(*) AS maillots 
                        FROM lleva l INNER JOIN ciclista c ON l.dorsal = c.dorsal
                          INNER JOIN equipo e ON c.nomequipo=e.nomequipo
                          INNER JOIN maillot m ON l.código = m.código
                        WHERE m.código="' . $codigo . '"
                        GROUP BY e.nomequipo, l.código
                        ORDER BY m.código asc, maillots DESC',
            'pagination' => false
        ]);
    }
    
    public static function maillotsYDineroPorCiclista() {
        return new SqlDataProvider([
            'sql' => 'SELECT c.dorsal, c.nombre, COUNT(l.dorsal) AS maillots, SUM(m.premio) AS "Dinero en premios"
                        FROM ciclista c left JOIN lleva l ON c.dorsal = l.dorsal
                        LEFT JOIN maillot m ON l.código=m.código
                        GROUP BY c.dorsal
                        ORDER BY 4 desc',
            'pagination' => false
        ]);
    }
    
    public static function maillotsYDineroPorEquipo() {
        return new SqlDataProvider([
            'sql' => 'SELECT  e.nomequipo, COUNT(l.dorsal) AS maillots, SUM(m.premio) AS "Dinero ganado"
                        FROM equipo e INNER JOIN ciclista c USING (nomequipo) LEFT JOIN lleva l ON c.dorsal = l.dorsal
                        LEFT JOIN maillot m ON l.código=m.código
                        GROUP BY e.nomequipo
                        ORDER BY 3 desc',
            'pagination' => false
        ]);
    }
    
    public static function puertosPorCiclista() {
        return new SqlDataProvider([
            'sql' => 'SELECT c.dorsal, c.nombre, COUNT(*) AS "Puertos Ganados"
                        FROM ciclista c INNER JOIN puerto p USING (dorsal)
                        GROUP BY c.dorsal',
            'pagination' => false
        ]);
    }
    
    public static function puertosPorEquipo() {
        return new SqlDataProvider([
            'sql' => 'SELECT c.nomequipo, COUNT(*) AS "Puertos Ganados"
                        FROM ciclista c INNER JOIN puerto p USING (dorsal)
                        GROUP BY c.nomequipo',
            'pagination' => false
        ]);
    }
    
    public static function ganadoresMaillotFinal() {
        return new SqlDataProvider([
            'sql' => 'SELECT m.color, m.tipo, c.dorsal, c.nombre, e.nomequipo, e.director
                        FROM (SELECT * FROM lleva
                        WHERE numetapa=(SELECT MAX(numetapa) FROM etapa))AS l
                        INNER JOIN maillot m USING (código)
                        INNER JOIN ciclista c USING (dorsal)
                        INNER JOIN equipo e USING (nomequipo)
                      UNION
                      SELECT m.color, m.tipo, c.dorsal, c.nombre, e.nomequipo, e.director

views/site/_resultado.php
<?php
    use app\controllers\SiteController;
    use yii\grid\GridView;
?>

<div style="display: flex; justify-content: space-between">
    <div class="column-md-5">
        <h2 class="text-center">Ciclistas que han ganado el maillot <?= $model->color ?> en cada etapa</h2>
        <?= GridView::widget([
            'dataProvider' => SiteController::ciclistasConMaillots($model->código),
            'columns' => [
                'dorsal',
                'nombre',
                'etapa',
                'salida',
                'llegada'
            ],
            'summary' => '',
        ]); ?>
    </div>
    <div class="column-md-2"> </div>
    <div class="column-md-5">
        <h2 class="text-center">Equipos que han ganado el maillot <?= $model->color ?> en cada etapa</h2>
        <?= GridView::widget([
            'dataProvider' => SiteController::equiposConMaillotsTipo($model->código),
            'columns' => [
                'nomequipo',
                'maillots'
            ],
            'summary' => '',
        ]); ?>
    </div>
    
    
</div>

views/site/about.php
<?php

/** @var yii\web\View $this */
use yii\helpers\Html;

$this->title = 'El Equipo Noam Chomsky';
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="site-about">
    <h1 class="equiponoam text-center"><?= Html::encode($this->title) ?></h1>
        
    <div class="row" >
        <div class="col-md-2">
            
        </div>
        <div class="col-md-8 text-center">
            <p>Bienvenido a la página sobre el Grupo Noam Chomsky. Somos un equipo de desarrolladores comprometidos y apasionados por la creación de soluciones innovadoras.</p>
        </div>
        <div class="col-md-2">
            
        </div>
    </div>

    <div class="members">
        <div class="member">
            <?= Html::img('@web/img/Pablo.jpg', ['alt' => 'Pablo Díaz']) ?>
            <p>Pablo Díaz</p>
        </div>
        <div class="member">
            <?= Html::img('@web/img/Saul.jpg', ['alt' => 'Saúl Crespo']) ?>
            <p>Saúl Crespo</p>
        </div>
        <div class="member">
            <?= Html::img('@web/img/Keyla.jpg', ['alt' => 'Keyla Condori']) ?>
            <p>Keyla Condori</p>
        </div>
        <div class="member">
            <?= Html::img('@web/img/German.jpg', ['alt' => 'Germán Santos']) ?>
            <p>Germán Santos</p>
        </div>
        <div class="member">
            <?= Html::img('@web/img/Yoel.jpg', ['alt' => 'Yoel Suero']) ?>
            <p>Yoel Suero</p>
        </div>
    </div>

    <div class="additional-info">
        <h2 class="equiponoam text-center">Contacto con el Ciclismo</h2>
        
        
        <div class="row" >
            <div class="col-md-2 text-center">

            </div>
            <div class="col-md-8 text-center">
                <p>En Grupo Noam Chomsky, aunque somos principalmente un equipo de desarrollo de software, también nos apasiona el ciclismo. Nos inspira ver a los ciclistas desafiando sus límites y superando obstáculos en cada pedalada. </p>
            </div>
            <div class="col-md-2 text-center">

            </div>
        </div>
    </div>

    <div class="quote-container">
        <div class="quote quote-blue">
            <strong>Pablo Díaz:</strong>
            <p>"El ciclismo no es mi deporte favorito, pero me gusta verlo de vez en cuando"</p>
        </div>
        <div class="quote quote-black">
            <strong>Saúl Crespo:</strong>
            <p>"El ciclismo es una gran forma de desconectar y disfrutar del aire libre"</p>
        </div>
        <div class="quote quote-red">
            <strong>Keyla Condori:</strong>
            <p>"Me encanta la sensación de libertad que experimento al montar en bicicleta"</p>
        </div>
        <div class="quote quote-yellow">
            <strong>Germán Santos:</strong>
            <p>"El ciclismo es un desafío constante, tanto físico como mental"</p>
        </div>
        <div class="quote quote-green">
            <strong>Yoel Suero:</strong>
            <p>"El ciclismo me ayuda a mantenerme en forma y conocer nuevos lugares"</p>
        </div>
    </div>


    <div>
        
        <h2 class="equiponoam text-center opinion">Opinión del proyecto</h2>
        
        
        <div class="row" >
            <div class="col-md-1">
            
            </div>
            <div class="col-md-10 text-center">
                <p>Nos ha gustado trabajar con una base de ciclistas, esto ha dado libertad a nuestra imaginación. 
                Además, usar el framework Yii2 suponía un reto, y ver que conseguíamos añadir un color, una forma o un simple texto, nos alegrábamos mucho.
                <br>Cada parte de este proyecto está realizada con cariño y cuidada al máximo, todos nosotros nos hemos esforzado en hacer una página que destaque por 
                el cuidado en los detalles, tanto en los colores (haciendo referencias a los Juegos Olímpicos), como en los textos, imágenes, tablas...etc.
                <br>Esperamos que os guste nuestro trabajo y que os entre un poco el gusanillo de salir por ahí con la bicicleta a dar una vuelta.</p>
            </div>
            <div class="col-md-1">
            
            </div>
        </div>
    </div>

    
        <h2 class="equiponoam text-center opinion">¡Gracias por visitar nuestra página!</h2>
    
</div>

views/site/clasificacion.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $resultados array */

$this->title = 'Clasificación';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-clasificacion">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        'nombre',
        'equipo',
        'tiempo_total',
        // ... otras columnas según tu modelo de datos
        ['class' => 'yii\grid\ActionColumn'],
    ],
]); ?>
</div>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/crear.php
<?php

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */
use yii\bootstrap4\Html;
$this->title = 'crear';
?>

<div class="container">
    
    <div class="encabezado">
        <h3>¡Crea tus propios equipos y etapas!</h3>
        <p class="lead">¡Únete a la emoción y la aventura de la Vuelta a España creando tus propios equipos y diseñando etapas emocionantes! Con nuestra herramienta fácil de usar, podrás personalizar cada detalle para adaptarlo a tus preferencias y desafiar tus límites. ¡Deja volar tu imaginación y comienza tu viaje ahora mismo!</p>
    </div>
    
    <div class="row">

        <div class="imagencrear col-sm-6">
            <?= Html::img('@web/img/Logos/equipo-standard.jpg')?>
            <p class="text-center"><?= Html::a('Crear Equipos',['equipo/index'],['class'=>'btn btn-outline-primary'])?></p>
        </div>

        <div class="imagencrear col-sm-6">
            <?= Html::img('@web/img/bing/etapas.jpg')?>
            <p class="text-center"><?= Html::a('Crear Etapas',['etapa/index'],['class'=>'btn btn-outline-primary'])?></p>
        </div>
    </div>
    
    
    <div class="row">
    
    
    
    </div>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/** @var yii\web\View $this */

$this->title = 'Maillot Olímpico';
use yii\helpers\Html;
?>
<div class="site-index">

    

    <div class="body-content">
        <div class="row">
        <div class="col-md-4">

    </div>
        <div class="col-md-4">
            <div class="logo d-flex justify-content-center">
            <div class="zooming-text" data-text="Texto a brillar">
                <h2 class="nombreapp text-center zooming-text">MAILLOT</h2>
                <?= Html::img('@web/img/logo.png')?>
                <h2 class="nombreapp text-center zooming-text">OLÍMPICO</h2>
            </div>
            </div>
        </div>
        <div class="col-md-4">

    </div>
        
    </div>

views/site/iniciarvuelta.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;
/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */
?>
<div style="display: flex;">
    <div class="iniciar">
        <div class="nombre-imagen column-md-4">
            <h2 class="text-center">BIENVENIDOS AL SIMULADOR</h2>
            <?= Html::img('@web/img/bing/ciclistasolimpicos1.jpg')?>
            <p class="text-center">Aqui puedes ver a todos los intrépidos ciclistas que se medirán en una gran
                carrera que les llevará al límite, hasta que finalmente uno de ellos se proclame 
                campeón del Maillot Olímpico. No subestimes a ninguno de los corredores, todos son 
                capaces de ganar esta carrera llena de obstaulos y superación personal.</p>
        </div>

        <div class="nombre-imagen column-md-4">
            <h2 class="text-center">BUENA SUERTE A TODOS</h2>
            <?= Html::img('@web/img/bing/corredores.jpg')?>
            <p class="text-center">Si estás entre los ciclistas, te deseamos la mejor de las suertes, ya que tendrás que 
                competir contra autenticos campeones.<br>
                De todas formas sabemos que eres muy competitivo y que seguro quieres ganar.<br> 
                ¡Da lo mejor de tí para proclamarte campeón!</p>
        </div>
        
        <div class="nombre-imagen column-md-4">
            <h2 class="text-center">SIMULAR VUELTA CICLISTA</h2>
            <?= Html::img('@web/img/bing/correr.jpg')?>
            <p class="text-center">En cuanto presiones el botón INICIAR, comenzará una dura competición
            que enfrentará a todos los ciclistas de los diferentes equipos, compitiendo
            en todas las etapas para conseguir ganar la mayor cantidad de maillots
            posibles y lograr realizar la Vuelta a España en el menor tiempo posible.</p>
            
        </div>
    </div>

    <div style="width: 66.66%;">
        <div class="resultado">
            <h2 class="text-center">MI VUELTA A ESPAÑA</h2>
            <div style="display:flex;justify-content: space-between">
                <div>
                    <h2 class="init text-center">ETAPAS</h2>
                    <?= GridView::widget([
                        'dataProvider' => $etapas,
                        'columns' => [
                            'numetapa',
                            'salida',
                            'llegada',
                            'kms'
                        ],
                        'summary' => '',
                    ]); ?>
                    <p class="text-center"><?=Html::a('INICIAR VUELTA',['site/simular'],['class'=>'btn btn-outline-primary']) ?></p>
                </div>
                <div>
                    <h2 class="text-center">EQUIPOS</h2>
                    <?= GridView::widget([
                        'dataProvider' => $equipos,
                        'columns' => [
                            'nomequipo',
                            'director',
                        ],
                        'summary' => '',
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>